### ISSUE TITLE
path rewrite (?) cause file not found error during edit.

### ISSUE THREAD

**Issue by unional** [wallabyjs/walllaby-typescript-powerassert#2]
This is a bit hard to describe but I can reproduce it.

Following #1 , if I start Wallaby, and then change the test to:
```ts
    it('should greet', () => {
        var greeter = new Greeter('John');
        expect(gretter.greet(), 'asdf')
    });
```

There seems to be some path rewrite going on and cause the file lookup to failed (`./src/src/greeter.unit.js` instead of `./src/greeter.unit.js`).

If I comment out the `preprocessors` in `wallaby.js`, it is working fine (the `setup` does not contribute to this).

```sh
​​​​​1 failing tests, 0 passing​​​​​
​​​​​​​​​​
​​Error: ENOENT: no such file or directory, open './src/src/greeter.unit.js'​​
​​    at Object.fs.openSync (fs.js:653:18)​​
​​    at Object.fs.readFileSync (fs.js:554:33)​​
​​    at exports.formatStackTrace (/Users/hwong/github/wallabyjs/walllaby-typescript-powerassert/node_modules/jest-message-util/build/index.js:232:20)​​
​​    at failedResults.map (/Users/hwong/github/wallabyjs/walllaby-typescript-powerassert/node_modules/jest-message-util/build/index.js:278:5)​​
​​    at Array.map (<anonymous>)​​
​​    at exports.formatResultsErrors (/Users/hwong/github/wallabyjs/walllaby-typescript-powerassert/node_modules/jest-message-util/build/index.js:273:3)​​
​​    at Jasmine2Reporter.jasmineDone (/Users/hwong/github/wallabyjs/walllaby-typescript-powerassert/node_modules/jest-jasmine2/build/reporter.js:103:64)​​
​​    at dispatch (/Users/hwong/github/wallabyjs/walllaby-typescript-powerassert/node_modules/jest-jasmine2/build/jasmine/report_dispatcher.js:70:26)​​
​​    at ReportDispatcher.jasmineDone (/Users/hwong/github/wallabyjs/walllaby-typescript-powerassert/node_modules/jest-jasmine2/build/jasmine/report_dispatcher.js:62:247)​​
​​    at Env.<anonymous> (/Users/hwong/github/wallabyjs/walllaby-typescript-powerassert/node_modules/jest-jasmine2/build/jasmine/Env.js:240:18)​​
​​    at Generator.next (<anonymous>)​​
​​    at step (/Users/hwong/github/wallabyjs/walllaby-typescript-powerassert/node_modules/jest-jasmine2/build/jasmine/Env.js:529:500)​​
​​    at /Users/hwong/github/wallabyjs/walllaby-typescript-powerassert/node_modules/jest-jasmine2/build/jasmine/Env.js:529:660​​
​​    at <anonymous>​​
  
  ​​​​Sayings Greeter should greet​​​​ ​​​[5 ms]​​​​
    ​​​​
    ​​ReferenceError: gretter is not defined​​
```

**Comment by ArtemGovorov** [comment]
I think it is related to the fact that power assert doesn't seem to support Jest https://github.com/wallabyjs/walllaby-typescript-powerassert/issues/1#issuecomment-354597195. 

You may comment out out the `preprocessors` section (that is trying to do power-assert transform) and the error goes away, as you have already noticed.

**Comment by ArtemGovorov** [comment]
Actually, I have found the reason for this one. Try the following preprocessor, it should work:


```javascript
    preprocessors: {
      '**/*.unit.js': file => {
        const sourceMapCommentRegEx = /\/\/[@#] sourceMappingURL=data:application\/json(?:;charset[:=][^;]+)?;base64,(.*)\n/;
        var getSourceMapFromDataUrl = function (code) {
          const match = code.match(sourceMapCommentRegEx);
          const sourceMapBase64 = match[1];
          return JSON.parse(new Buffer(sourceMapBase64, 'base64').toString());
        };
        var transformedCode = require('espower-source')(
          file.content.replace('(\'assert\')', '(\'power-assert\')'),
          file.path);
        return {code: transformedCode.replace(sourceMapCommentRegEx, ''), sourceMap: getSourceMapFromDataUrl(transformedCode)};
      }
    },
```

Doesn't fix the other issues with inline messages though. That other issue is definitely caused by incompatibility of power-assert and Jest.

**Comment by unional** [comment]
Thanks. Yes, that does fix it.
